export const SELECT_SONG = 'SELECT_SONG'
export const ADD_SONG = 'ADD_SONG'

export const ADD_TO_SETLIST = 'ADD_TO_SETLIST'
export const REMOVE_FROM_SETLIST = 'REMOVE_FROM_SETLIST'
export const SONG_ALREADY_ADDED = 'SONG_ALREADY_ADDED'

export const UPDATE_LOCATIONS_FILTERS = 'UPDATE_LOCATIONS_FILTERS'
export const UPDATE_LANGUAGES_FILTERS = 'UPDATE_LANGUAGES_FILTERS'
export const UPDATE_STYLES_FILTERS = 'UPDATE_STYLES_FILTERS'
export const UPDATE_MATCHING_OPTION = 'UPDATE_MATCHING_OPTION'
export const EXPAND_FILTER_GROUP = 'EXPAND_FILTER_GROUP'
export const UPDATE_SEARCH = 'UPDATE_SEARCH'